[test]
name = "structs"
description = "Simple structs example"

parser = "pass"
# These dont really "pass" in the sense that we never lower it to mir, so it wont do anything, but it also wont panic
mir = "pass"
vm  = "pass"
